name: format-lint-unittest

on:
  - pull_request
  - push

jobs:
  format-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: format
        run: docker run --privileged -e TERM=xterm-256color -v $PWD:/home/user/protobuf-ipc-example --network host limjk/protobuf-ipc-example /bin/sh -c 'cd /home/user/protobuf-ipc-example && export PATH=/home/user/.local/bin:$PATH && ./run_check.sh format'
      - name: lint
        run: docker run --privileged -e TERM=xterm-256color -v $PWD:/home/user/protobuf-ipc-example --network host limjk/protobuf-ipc-example /bin/sh -c 'cd /home/user/protobuf-ipc-example && export PATH=/home/user/.local/bin:$PATH && ./run_check.sh lint'
      - name: doc_check
        run: docker run --privileged -e TERM=xterm-256color -v $PWD:/home/user/protobuf-ipc-example --network host limjk/protobuf-ipc-example /bin/sh -c 'cd /home/user/protobuf-ipc-example && export PATH=/home/user/.local/bin:$PATH && ./run_check.sh doc_check'
      - name: all
        run: docker run --privileged -e TERM=xterm-256color -v $PWD:/home/user/protobuf-ipc-example --network host limjk/protobuf-ipc-example /bin/sh -c 'cd /home/user/protobuf-ipc-example && export PATH=/home/user/.local/bin:$PATH && ./run_check.sh all'

  build-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: build 
        run: docker run --privileged -e TERM=xterm-256color -v $PWD:/home/user/protobuf-ipc-example --network host limjk/protobuf-ipc-example /bin/sh -c 'cd /home/user/protobuf-ipc-example && export PATH=/home/user/.local/bin:$PATH && ./run_check.sh build'

  unit-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build and unit test
        run: docker run --privileged -e TERM=xterm-256color -v $PWD:/home/user/protobuf-ipc-example --network host limjk/protobuf-ipc-example /bin/sh -c 'cd /home/user/protobuf-ipc-example && export PATH=/home/user/.local/bin:$PATH && ./run_check.sh test'
